<?php

/**
 * BaseUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $url
 * @property string $domain
 * @property enum $type
 * @property enum $status
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
abstract class BaseUrl extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('url');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
    $this->hasColumn('code', 'string', 256, array('type' => 'string', 'length' => 256, 'notnull' => true));
    $this->hasColumn('url', 'string', 1024, array('type' => 'string', 'length' => 1024, 'notnull' => true));
    $this->hasColumn('domain', 'string', 256, array('type' => 'string', 'length' => 256, 'notnull' => true));
    $this->hasColumn('type', 'enum', 5, array('type' => 'enum', 'length' => 5, 'values' => array(0 => 'url', 1 => 'email', 2 => 'text', 3 => 'image'), 'notnull' => true));
    $this->hasColumn('status', 'enum', 7, array('type' => 'enum', 'length' => 7, 'values' => array(0 => 'active', 1 => 'passive', 2 => 'deleted'), 'notnull' => true));
  }

}