<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $created_by
 * @property timestamp $created_on
 * @property enum $status
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
abstract class BaseUser extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('user');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true));
    $this->hasColumn('username', 'string', 256, array('type' => 'string', 'length' => 256, 'notnull' => true));
    $this->hasColumn('password', 'string', 512, array('type' => 'string', 'length' => 512, 'notnull' => true));
    $this->hasColumn('email', 'string', 512, array('type' => 'string', 'length' => 512, 'notnull' => true));
    $this->hasColumn('created_by', 'string', 32, array('type' => 'string', 'length' => 32, 'notnull' => true));
    $this->hasColumn('created_on', 'timestamp', null, array('type' => 'timestamp', 'notnull' => true));
    $this->hasColumn('status', 'enum', 7, array('type' => 'enum', 'length' => 7, 'values' => array(0 => 'pending', 1 => 'live', 2 => 'dead'), 'notnull' => true));
  }

}