<?php

/**
 * BaseStatistic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $st_key
 * @property string $st_value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
abstract class BaseStatistic extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('statistic');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'notnull' => true));
    $this->hasColumn('st_key', 'string', 256, array('type' => 'string', 'length' => 256, 'notnull' => true));
    $this->hasColumn('st_value', 'string', 512, array('type' => 'string', 'length' => 512, 'notnull' => true));
  }

}