<?php

/**
 * BaseOwnership
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $url_id
 * @property string $created_by
 * @property timestamp $created_on
 * @property enum $type
 * @property enum $status
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
abstract class BaseOwnership extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('ownership');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
    $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'notnull' => true));
    $this->hasColumn('url_id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'notnull' => true));
    $this->hasColumn('created_by', 'string', 32, array('type' => 'string', 'length' => 32, 'notnull' => true));
    $this->hasColumn('created_on', 'timestamp', null, array('type' => 'timestamp', 'notnull' => true));
    $this->hasColumn('type', 'enum', 9, array('type' => 'enum', 'length' => 9, 'values' => array(0 => 'created', 1 => 'favorited'), 'notnull' => true));
    $this->hasColumn('status', 'enum', 4, array('type' => 'enum', 'length' => 4, 'values' => array(0 => 'live', 1 => 'dead'), 'notnull' => true));
  }

}