<h2>Privacy Policy</h2>
We do not collect any personally identifying information from users of this website. We store only the technical
information necessary to provide our URL shortening service, such as the original long URLs. We may also store the IP
addresses of computers using the kissa.be service (and similar usage information such as web browser/resolution) for the
sole purposes of identifying abuse of the service and tracking anonymous usage trends. This information will not be made
available to third parties.<p/>

URLs shortened by our website are not private and should not be treated as such. Third parties could easily guess the
short URL that you are using, so you should not use kissa.be to link to sensitive or secure data.
