<h2>Terms Of Use</h2>

<h3>Forbidden activities</h3>

kissa.be may not be used for the following: <p/>

<ul>
<li>Creating URLs for use in unsolicited advertising including but not limited to email and forum posts (i.e. do not use for SPAM purposes)</li>
<li>Linking to any file or website depicting actual or simulated child pornography</li>
<li>Linking to any content which is illegal in your area</li>
<li>Any other use which is illegal in your area</li>
</ul>

We reserve the right to remove any shortened URLs which we deem to have violated our terms and conditions, or that we believe violate the spirit of our terms or of fair usage (at our discretion).

<h3>Warranty</h3>
kissa.be is provided as a free service, and as such carries no warranty of any kind. kissa.be is not liable for any loss or problem you might suffer due to using the service. This includes losses in the event that the service stops operating, is unavailable or slow, suffers data loss, or any other issue which might be considered detrimental to you.


