<form action="{%uri path="/shortener/set"}" method="post" onsubmit="return checkform(this);">
<input class="textbox" maxlength="2000" size="55" id="content_data" name="content_data" value="" type="text">
<input value="url" name="status" type="hidden">
<input class="button" value="shorten this" type="submit">
</form>
